GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
  "text":"Da"
}

###

DELETE http://localhost:3001/todo/delete/6460c88f6e0ee7a9cc712d5e

###

PUT http://localhost:3001/todo/complete/645d6673e9cc846fdb47c7f4